### PR TITLE
Ahk lv1.1

### PR DESCRIPTION
**Pull request by hoppfrosch**
Some modifications (as discussed via pm) to work properly with latest library modules

Examples for TaskBarList3: 
[+] added missing include
[+] Simple usage instrcutions

### CODE REVIEW

**Comment by maul-esel** [comment]
**Sorry I can't merge this :(** You took the AHK_L version and ask me to merge it in to the AHK v2 version.
Please redo your changes in the "master" branch and then send me a new pull request.

Besides that, thanks for your efforts.

**Comment by hoppfrosch** [comment]
Ooops - this shows that I'm still a git-learner ... Will do it ....

I have to find out, how correctly work with branches within git ... (In fact I did the changes only on AHK_L branch - and what I wanted to do is a pull request on your "AHK_L"-branch. Obviously I did something wrong, since "I asked you to merge it in to the AHK v2 version." (and not to branch AHK_L as planned ...))

**Comment by maul-esel** [comment]
No problem.
However, I'd prefer changes being made to the master branch, so I can merge it in the AHK_Lv1.1 branch more easily. Would be great if that is possible.

**Comment by hoppfrosch** [comment]
This means I have to test it with AHK2 on the master branch as well with AHK1.1 on branch AHK_L? I haven't used AHK2 yet - but shouldn't be a problem ...

**Comment by maul-esel** [comment]
Testing for AHK v2 should suffice. I'll merge the "master" branch into AHK_Lv1.1 then and do the appropriate changes.

**Pull request closed without merging**
